### ISSUE TITLE
DefaultQA ERRORS when using SolrProvider

### ISSUE THREAD

**Issue by Ruil** [oaqa/solr-provider#2]
Before I added solrprovider into maven's dependency, everything is good. But after I added this guy, I got errors in the class.edu.cmu.lti.oaqa.bio.framework.report.DatabaseReportComponentBuilder. For example,

Description Resource Path Location Type
The type com.google.common.collect.Table cannot be resolved. It is indirectly referenced from required .class files DatabaseReportComponentBuilder.java /DefaultQA/src/main/java/edu/cmu/lti/oaqa/bio/framework/report line 1 Java Problem

Any idea?

**Comment by elmer-garduno** [comment]
Which version of solr-provider are you using, could you paste your Maven dependency tag?

**Comment by Ruil** [comment]
[image: Inline image 1]

**Comment by elmer-garduno** [comment]
Your Maven `<dependency>` tag?

**Comment by Ruil** [comment]
e...? What do you mean? My DefaultQA's pom is here:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="
http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<groupId>edu.cmu.lti.oaqa.bio.core</groupId>
<artifactId>defaultqa</artifactId>
<version>1.2.18-SNAPSHOT</version>
<parent>
<groupId>edu.cmu.lti.oaqa</groupId>
<artifactId>oaqa</artifactId>
<version>4</version>
</parent>
<scm>
<connection>scm:svn:svn://
mu.lti.cs.cmu.edu/bio/trunk/edu.cmu.lti.oaqa.bio.core.DefaultQA</connection>
<developerConnection>scm:svn:svn://
mu.lti.cs.cmu.edu/bio/trunk/edu.cmu.lti.oaqa.bio.core.DefaultQA
</developerConnection>
</scm>
<repositories>
<repository>
<id>oaqa</id>
<url>http://mu.lti.cs.cmu.edu:8081/nexus/content/groups/public</url>
</repository>
</repositories>
<profiles>
<profile>
<id>osx</id>
<activation>
<os>
<family>mac</family>
</os>
</activation>
<properties>
<build.type>jnilib</build.type>
<build.artifact>libindri_jni</build.artifact>
<build.name>libindri_jni</build.name>
</properties>
<dependencies>
<dependency>
<groupId>org.lemurproject</groupId>
<artifactId>indri</artifactId>
<version>5.2</version>
<type>jar</type>
<scope>compile</scope>
</dependency>
</dependencies>
</profile>
<profile>
<id>x86-windows</id>
<activation>
<os>
<family>Windows</family>
<arch>x86</arch>
</os>
</activation>
<properties>
<build.type>dll</build.type>
<build.artifact>indri_jni</build.artifact>
<build.name>indri_jni</build.name>
</properties>
<dependencies>
<dependency>
<groupId>org.lemurproject</groupId>
<artifactId>indri</artifactId>
<version>5.2</version>
<type>jar</type>
<scope>compile</scope>
</dependency>
</dependencies>
</profile>
<profile>
<id>x64-nix</id>
<activation>
<os>
<name>Linux</name>
<arch>amd64</arch>
</os>
</activation>
<properties>
<build.type>so</build.type>
<build.artifact>libindri_jni_64</build.artifact>
<build.name>libindri_jni</build.name>
</properties>
<dependencies>
<dependency>
<groupId>org.lemurproject</groupId>
<artifactId>indri_64</artifactId>
<version>5.2</version>
<type>jar</type>
<scope>compile</scope>
</dependency>
</dependencies>
</profile>
<profile>
<id>x64-amd-windows</id>
<activation>
<os>
<family>Windows</family>
<arch>amd64</arch>
</os>
</activation>
<properties>
<build.type>dll</build.type>
<build.artifact>indri_jni_64</build.artifact>
<build.name>indri_jni</build.name>
</properties>
<dependencies>
<dependency>
<groupId>org.lemurproject</groupId>
<artifactId>indri_64</artifactId>
<version>5.2</version>
<type>jar</type>
<scope>compile</scope>
</dependency>
</dependencies>
</profile>
<profile>
<id>x64-windows</id>
<activation>
<os>
<family>Windows</family>
<arch>x86_64</arch>
</os>
</activation>
<properties>
<build.type>dll</build.type>
<build.artifact>indri_jni_64</build.artifact>
<build.name>indri_jni</build.name>
</properties>
<dependencies>
<dependency>
<groupId>org.lemurproject</groupId>
<artifactId>indri_64</artifactId>
<version>5.2</version>
<type>jar</type>
<scope>compile</scope>
</dependency>
</dependencies>
</profile>
</profiles>
<build>
<plugins>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-dependency-plugin</artifactId>
<version>2.4</version>
<executions>
<execution>
<id>copy</id>
<phase>generate-resources</phase>
<goals>
<goal>copy</goal>
</goals>
<configuration>
<artifactItems>
<artifactItem>
<groupId>org.lemurproject</groupId>
<artifactId>${build.artifact}</artifactId>
<version>5.2</version>
<type>${build.type}</type>
<overWrite>true</overWrite>
<outputDirectory>${project.build.directory}/lib</outputDirectory>
<destFileName>${build.name}.${build.type}</destFileName>
</artifactItem>
</artifactItems>
</configuration>
</execution>
</executions>
</plugin>
<plugin>
<groupId>org.codehaus.mojo</groupId>
<artifactId>exec-maven-plugin</artifactId>
<executions>
<execution>
<goals>
<goal>exec</goal>
</goals>
</execution>
</executions>
<configuration>
<executable>java</executable>
<arguments>
<argument>-Xmx2500m</argument>
<argument>-Djava.library.path=${project.build.directory}/lib/</argument>
<argument>-classpath</argument>



<classpath />
<argument>edu.cmu.lti.oaqa.ecd.driver.ECDDriver</argument>
<argument>default.default-test</argument>
</arguments>
</configuration>
</plugin>
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-compiler-plugin</artifactId>
<configuration>
<source>1.6</source>
<target>1.6</target>
</configuration>
</plugin>
</plugins>
<pluginManagement>
<plugins>



<plugin>
<groupId>org.eclipse.m2e</groupId>
<artifactId>lifecycle-mapping</artifactId>
<version>1.0.0</version>
<configuration>
<lifecycleMappingMetadata>
<pluginExecutions>
<pluginExecution>
<pluginExecutionFilter>
<groupId>
org.apache.maven.plugins
</groupId>
<artifactId>
maven-dependency-plugin
</artifactId>
<versionRange>
[2.4,)
</versionRange>
<goals>
<goal>copy</goal>
</goals>
</pluginExecutionFilter>
<action>
<ignore />
</action>
</pluginExecution>
</pluginExecutions>
</lifecycleMappingMetadata>
</configuration>
</plugin>
</plugins>
</pluginManagement>
</build>
<dependencies>
<dependency>
<groupId>edu.cmu.lti.oaqa.bio.core.provider</groupId>
<artifactId>indri-provider</artifactId>
<version>1.1.1</version>
</dependency>
    <dependency>
      <groupId>edu.cmu.lti.oaqa.bio.core</groupId>
      <artifactId>baseqa</artifactId>
      <version>1.7.0</version>
    </dependency>
    <dependency>
      <groupId>edu.cmu.lti.oaqa.bio.model</groupId>
      <artifactId>bio-model</artifactId>
      <version>1.0.1</version>
    </dependency>
    <dependency>
    <groupId>edu.cmu.lti.oaqa.framework.impl</groupId>
    <artifactId>jdbc-providers</artifactId>
    <version>2.2.0</version>
    </dependency>
    <dependency>
    <groupId>edu.cmu.lti.oaqa.core.provider</groupId>
    <artifactId>solr-provider</artifactId>
    <version>1.0.4</version>
    </dependency>
</dependencies>
</project>

**Comment by elmer-garduno** [comment]
Please use version 1.0.5

```
<dependency> 
 <groupId>edu.cmu.lti.oaqa.core.provider</groupId> 
 <artifactId>solr-provider</artifactId> 
 <version>1.0.5</version> 
</dependency> 
```

**Comment by Ruil** [comment]
Hi Elmer,
I changed 1.0.4 to 1.0.5 and I've updated the Maven project, but I still
have the error:
[image: Inline image 1]

**Comment by Ruil** [comment]
btw, I didn't have any errors before adding solr-provider.

Thanks,
Rui

**Comment by elmer-garduno** [comment]
I understand, what's happening is that you didn't reach that point of the code before, because you didn't had a provider; so no info -> no evaluation. And the error is coming from the evaluation code.

The problem seems to be on DefaultQA. Can you see a google-guava dependency on the Dependency Hierarchy tab?

**Comment by Ruil** [comment]
Yes, I can see that.

[image: Inline image 1]

**Comment by elmer-garduno** [comment]
Ok, I fixed it, can you update DefaultQA. The problem was a bad transitive dependency on an old version of guava, that comes with solr.

**Comment by Ruil** [comment]
Nice! I'll do it.
