### ISSUE TITLE
Could we access the inverted list? Or just configure the Solr in Runtime?

### ISSUE THREAD

**Issue by MagIciaNGTAO** [oaqa/solr-provider#4]
Hi, 

This is team-16 in Professor Eric's Software Engineering course.

We have assigned two people working on Retrieval part. We want to know what kind of flexibility is in our hands.
1. Could we access the inverted list or plug-in any our own retrieval algorithms? 
2. Could we configure the Solr behavior in Runtime?

Thank you in advance!
Best Regards,
Team 16

**Comment by elmer-garduno** [comment]
There is code on the feature_snippets branch that allows you to pass a pre-configured SolrQuery. You can also modify the index parameters to add different on the solrconfig.xml file on your helloqa. 

@amaiberg, @alkeshpatel11 should we merge the feature_snippets branch and release a new version?

**Comment by elmer-garduno** [comment]
There seems to be some useful information in here:

http://wiki.apache.org/solr/SolrRelevancyFAQ

http://lucene.apache.org/core/old_versioned_docs/versions/3_5_0/scoring.html

**Comment by MagIciaNGTAO** [comment]
Thank you a lot!
